####
POST http://localhost:3000/auth/registro
Content-Type: application/json

{
    "username": "usuarioEjemplo",
    "email": "usuario@example.com",
    "password": "contraseña123",
    "direccion": "Calle Ejemplo 123",
    "role": 1
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "aa",
  "contrasena": "aa"
}